run:
	g++ -O3 -std=c++20 padding.cpp -static -static-libgcc -static-libstdc++ -lstdc++fs -o padding
	g++ -O0 -g -std=c++20 debug_binpack.cpp -static -static-libgcc -static-libstdc++ -lstdc++fs -o debug_binpack